kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.23
  commands:
    - go mod download
    - go build -o app

- name: test
  image: golang:1.23
  commands:
    - go test ./...

- name: docker
  image: plugins/docker
  settings:
    username: SrgBr0
    password: 
      from_secret: Serega2146fcb
    repo: SrgBr0/НАЗВАНИЕ_РЕПОЗИТОРИЯ
    tags: 
      - latest
      - ${DRONE_COMMIT_SHA:0:7}
