name: CI for Go Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        run: |
          docker build -t go-docker-example .

      - name: Run the application in Docker
        run: |
          docker run --rm go-docker-example
