name: Build and Deploy Go App with Docker

on:
  push:
    branches:
      - ci_not_main  # Запускать на push в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверяем код
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Docker Buildx для оптимизации сборки
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Пересобираем Docker образ
      - name: Build Docker image
        run: |
          docker build -t go-web-app .

      # Шаг 4: Останавливаем и удаляем старый контейнер (если он существует)
      - name: Stop and remove old container
        run: |
          container_id=$(docker ps -q -f name=go-web-app)
          if [ -n "$container_id" ]; then
            echo "Stopping and removing old container..."
            docker stop go-web-app
            docker rm go-web-app
          else
            echo "No old container found."
          fi

      # Шаг 5: Запускаем новый контейнер с тем же именем
      - name: Run Docker container
        run: |
          echo "Starting new container with updated image..."
          docker run -d -p 8080:8080 --name go-web-app go-web-app
